### ISSUE TITLE
progress.log contains confidential information

### ISSUE THREAD

**Issue by davidwagner** [mikeaboody/phishing-research#43]
`progress.log` contains confidential information:

```
Creating Output Directory for John Smith
broScripts/output/Joh/the/Matthew Chow/matthewchow95@gmail.com generated.
```

I suspect we shouldn't have names or email addresses in there.  Suggestion: use just the first 3 letters of the name, and truncate the rest, so we get something like:

```
Creating Output Directory for Mat...
broScripts/output/Mat/... generated.
```

That's probably enough to see that progress is being made, without disclosing sensitive information.

Also I see:

```
[[['/home/daw/phishing-research/broScripts/output/Apo/orv/Apoorva Dornadula/a_dornadula@yahoo.com/legit_emails.log', ...
```

That also looks like it has confidential information in it.

Actually, I'm not too clear what that latter stuff is.  If it's trying to dump a data structure that contains information about every email address seen and convert it to JSON, I suspect that's bad news: that sounds like the sort of thing that's not going to scale well and might cause the CPU to explode.  Not sure it makes sense to put this in `progress.log`.

**Comment by davidwagner** [comment]
I talked to Vern.  He says we shouldn't include even the first 3 letters of names/emails in logs that are sent to us.  So, I suggest removing those log lines from `progress.log`.  They can be replaced by a count (e.g., once every 10 minutes, output a count of the number of output directories generated).

**Comment by MatthewChow** [comment]
https://github.com/mikeaboody/phishing-research/pull/45 should fix this issue.

**Comment by davidwagner** [comment]
Not fully fixed yet -- I still see

```
[[['/home/daw/phishing-research/broScripts/output/Apo/orv/Apoorva Dornadula/...@yahoo.com/legit_emails.log',
```

in progress.log, and that contains confidential information (indeed, entire headers for some emails).
